export const env = {
  databaseUrl: process.env.DATABASE_URL || "",
  directUrl: process.env.DIRECT_URL || "",
  authCookieName: process.env.AUTH_COOKIE_NAME || "mip_session",
  appUrl: process.env.APP_URL || "http://localhost:3000",
  cronSecret: process.env.CRON_SECRET || "",
  datajudBaseUrl: process.env.DATAJUD_BASE_URL || "",
  datajudApiKey: process.env.DATAJUD_API_KEY || "",
  datajudUsePublicKeyFallback: process.env.DATAJUD_USE_PUBLIC_KEY_FALLBACK !== "false",
  datajudTribunalAlias: process.env.DATAJUD_TRIBUNAL_ALIAS || "",
  datajudTimeoutMs: Number(process.env.DATAJUD_TIMEOUT_MS || "15000"),
  djenBaseUrl: process.env.DJEN_BASE_URL || "",
  djenApiPath: process.env.DJEN_API_PATH || "/api/v1/comunicacao",
  djenTimeoutMs: Number(process.env.DJEN_TIMEOUT_MS || "15000"),
  djenInitialLookbackDays: Number(process.env.DJEN_INITIAL_LOOKBACK_DAYS || "180"),
  djenIncrementalLookbackDays: Number(process.env.DJEN_INCREMENTAL_LOOKBACK_DAYS || "15"),
  useMockConnectors: process.env.USE_MOCK_CONNECTORS !== "false",
};
